---
- name: ZSH | Configure ZSH tasks
  block:
    - name: ZSH | Deploy .extra on {{ ansible_facts['distribution'] }}
      ansible.builtin.template:
        src: extra.j2
        dest: "{{ zsh_user.home_dir | default('/home/') }}{{ zsh_user.name }}/.extra"
        mode: 0777

    - name: ZSH | Deploy .bash_profile on {{ ansible_facts['distribution'] }}
      ansible.builtin.template:
        src: bash_profile.j2
        dest: "{{ zsh_user.home_dir | default('/home/') }}{{ zsh_user.name }}/.bash_profile"
        mode: 0777

    - name: ZSH | Deploy .zshrc on {{ ansible_facts['distribution'] }}
      ansible.builtin.template:
        src: zshrc.j2
        dest: /usr/local/share/oh-my-zsh/conf/zshrc
        mode: 0777

    - name: ZSH | Remove standard zshrc on {{ ansible_facts['distribution'] }}
      ansible.builtin.file:
        path: "{{ zsh_user.home_dir | default('/home/') }}{{ zsh_user.name }}/.zshrc"
        state: absent
      changed_when: false

    - name: ZSH | Symlink zshrc on {{ ansible_facts['distribution'] }}
      ansible.builtin.file:
        path: "{{ zsh_user.home_dir | default('/home/') }}{{ zsh_user.name }}/.zshrc"
        src: /usr/local/share/oh-my-zsh/conf/zshrc
        state: link
        mode: 0777
      changed_when: false

    - name: ZSH | Set zsh as default shell on {{ ansible_facts['distribution'] }}
      ansible.builtin.shell: "chsh -s $(which zsh) {{ zsh_user.name }}"
      changed_when: false

  when: zsh_user != "{}"
  become: true

  rescue:
    - name: ZSH | Configuration zsh errors on {{ ansible_facts['distribution'] }}
      ansible.builtin.debug:
        msg: "I caught a configuration zsh errors on {{ ansible_facts['distribution'] }}"
