---
- name: ZSH | Configure ZSH tasks on {{ ansible_facts['distribution'] }}
  become: true
  when:
    - zsh_user | length > 0
  block:
    - name: ZSH | Deploy .extra on user {{ zsh_user.name }}
      ansible.builtin.template:
        src: extra.j2
        dest: "{{ zsh_user.home_dir | default('/home/') }}{{ zsh_user.name }}/.extra"
        owner: "{{ zsh_user.name }}"
        group: "{{ zsh_user.name }}"
        mode: '0600'

    - name: ZSH | Deploy .bash_profile on user {{ zsh_user.name }}
      ansible.builtin.template:
        src: bash_profile.j2
        dest: "{{ zsh_user.home_dir | default('/home/') }}{{ zsh_user.name }}/.bash_profile"
        owner: "{{ zsh_user.name }}"
        group: "{{ zsh_user.name }}"
        mode: '0600'

    - name: ZSH | Deploy .zshrc on user {{ zsh_user.name }}
      ansible.builtin.template:
        src: zshrc.j2
        dest: /usr/local/share/oh-my-zsh/conf/zshrc
        mode: '0600'

    - name: ZSH | Remove standard zshrc on user {{ zsh_user.name }}
      ansible.builtin.file:
        path: "{{ zsh_user.home_dir | default('/home/') }}{{ zsh_user.name }}/.zshrc"
        state: absent
      changed_when: false

    - name: ZSH | Symlink zshrc on user {{ zsh_user.name }}
      ansible.builtin.file:
        src: /usr/local/share/oh-my-zsh/conf/zshrc
        path: "{{ zsh_user.home_dir | default('/home/') }}{{ zsh_user.name }}/.zshrc"
        state: link
        owner: "{{ zsh_user.name }}"
        group: "{{ zsh_user.name }}"
        mode: u=rw,g=r,o=r
      changed_when: false

    - name: ZSH | Set zsh as default shell on user {{ zsh_user.name }}
      ansible.builtin.shell: "usermod --shell $(which zsh) {{ zsh_user.name }}"
      changed_when: false

  rescue:
    - name: ZSH | Configuration zsh errors on {{ ansible_facts['distribution'] }}
      ansible.builtin.debug:
        msg: "I caught a configuration zsh errors on {{ ansible_facts['distribution'] }}"
