---
# tasks file for role-zsh
- name: ZSH | Ensure git was installed on {{ ansible_facts['distribution'] }}
  ansible.builtin.package:
    name: git
    state: present
  become: true

- name: ZSH | Ensure zsh was installed on {{ ansible_facts['distribution'] }}
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: ZSH | Setup oh-my-zsh
  ansible.builtin.git:
    depth: 1
    repo: "{{ item.name }}"
    version: "{{ item.version }}"
    dest: /usr/local/share/{{ item.dir }}
  loop: "{{ zsh_ohmyzsh_source }}"

- name: ZSH | Setup ZSH plugins
  ansible.builtin.git:
    depth: 1
    repo: "{{ item.name }}"
    version: "{{ item.version }}"
    dest: /usr/local/share/{{ item.dir }}
  loop: "{{ zsh_zsh_plugins_source }}"

- name: ZSH | Create conf & cache folder in oh-my-zsh directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "/usr/local/share/oh-my-zsh/conf/"
    - "/usr/local/share/oh-my-zsh/cache/"

- name: ZSH | Setup zsh for default root user
  ansible.builtin.include_tasks: configure_zsh.yml
  loop: "{{ zsh_default_user }}"
  loop_control:
    loop_var: zsh_user
  when: zsh_default_user != "{}"

- name: ZSH | Setup zsh for common users
  ansible.builtin.include_tasks: configure_zsh.yml
  loop: "{{ zsh_users }}"
  loop_control:
    loop_var: zsh_user
  when: zsh_users != "{}"
