---
name: Publish on Ansible Galaxy

on:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  publish:
    name: Publish on Ansible Galaxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v1
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
